### ISSUE TITLE
ImportError: No module named utils.frozenutils

### ISSUE THREAD

**Issue by MathijsStrijards** [sharppy/SHARPpy#87] opened 2015-12-27 12:08 UTC
full_gui.py is unable to open the module utils

SHARPpy/runsharp$ python full_gui.py
Traceback (most recent call last):
  File "full_gui.py", line 4, in <module>
    import utils.frozenutils as frozenutils
ImportError: No module named utils.frozenutils

**Comment by keltonhalbert** [comment] 2015-12-29 19:43
This tends to be an issue if the install script was not run.

Did you run "python setup.py install" before running the full_gui.py script?

**Comment by MetNL** [comment] 2015-12-29 21:40
Yes. But when I started over again it worked well all. The problem now is
that I can't import GFS data and that's a bit frustrating because that was
the only model showing data in The Netherlands

2015-12-29 20:43 GMT+01:00 Kelton Halbert <notifications@github.com>:

**Comment by keltonhalbert** [comment] 2015-12-30 03:43
Can you let me know what site(s) you are having issues with loading? I'll see if I can isolate if it's an error on our end of if it's the server we pull the GFS data from.

**Comment by tsupinie** [comment] 2015-12-30 04:44
I see the issue. The Bufkit file on the PSU server doesn't have a station ID, which is throwing off the decoder. I'll see if I can push a patch real quick.

**Comment by tsupinie** [comment] 2015-12-30 05:00
Okay, re-download the code, re-install, and try again.

**Comment by MetNL** [comment] 2015-12-30 10:31
Got everything working now. Hope the KNMI observed data will be added
someday but I'm pleased with the GFS results for now.
Thnx y'all!

2015-12-30 6:00 GMT+01:00 Tim Supinie <notifications@github.com>:

**Comment by tsupinie** [comment] 2015-12-30 15:53
You're welcome! Good to hear!

**Comment by keltonhalbert** [comment] 2015-12-30 18:44
Thanks for investigating Tim!

**Comment by MetNL** [comment] 2016-04-10 18:53
Hi there, I'm having some problems again. The American GFS station are able
to plot, but none of the European ones. I'm on windows 7 now using the
pre-compiled  binary. i tried installing the source, but ended up having
some trouble installing pyside into my conda enviroment.

2015-12-30 19:44 GMT+01:00 Kelton Halbert <notifications@github.com>:

**Comment by tsupinie** [comment] 2016-04-18 17:19
Yeah, I had someone ask about that on Twitter over the weekend, and I investigated. I'm not sure what the issue is/was, but recompiling the binary fixed it for the OS X version. I'll see if I can recompile another Windows 7 version tonight.

**Comment by MetNL** [comment] 2016-04-18 18:16
Ok, 'cause I got the source code working now. The problem with the I got
source code is that python occasionally crashes.

2016-04-18 19:19 GMT+02:00 Tim Supinie <notifications@github.com>:

**Comment by thebag5** [comment] 2016-04-24 09:49
Noob question, I'm running the exe version which runs fine for the US and surrounding countries ie: Canada but because I'm based in Romania nothing loads for me here. Says decoding file but then just stops. If i do the same process for the states it works fine. I am using the GFS from the drop down.

**Comment by tsupinie** [comment] 2016-05-02 04:40
Okay, I've uploaded some new binaries for Windows 7 and OS X. I'll try to get @keltonhalbert to compile a Windows 8.1 binary at some point. Can you let me know if those work?

**Comment by MetNL** [comment] 2016-05-02 08:19
The sounding picker worked, but when I selected a site it crashed.
Diagnostics:

 Problem signature:
  Problem Event Name:    APPCRASH
  Application Name:    SHARPpy.exe
  Application Version:    0.0.0.0
  Application Timestamp:    5121fefe
  Fault Module Name:    QtCore4.dll
  Fault Module Version:    4.8.4.0
  Fault Module Timestamp:    50c50b8c
  Exception Code:    c0000005
  Exception Offset:    0000000000029991
  OS Version:    6.1.7601.2.1.0.256.48
  Locale ID:    1043
  Additional Information 1:    c2e0
  Additional Information 2:    c2e0961c4cda1530ccd2ad70e3af2cbd
  Additional Information 3:    0a21
  Additional Information 4:    0a21c74b5adcff9c3b30bbda51cecce7

2016-05-02 6:40 GMT+02:00 Tim Supinie <notifications@github.com>:

**Comment by tsupinie** [comment] 2016-05-02 13:50
Which binary are you using?

**Comment by MetNL** [comment] 2016-05-02 14:31
The 64 bits one

2016-05-02 15:50 GMT+02:00 Tim Supinie <notifications@github.com>:

**Comment by wblumberg** [comment] 2017-06-02 22:35
@MetNL are you still having this issue?

**Comment by Meteodan** [comment] 2018-06-01 22:33
Hi all,

I am receiving this same error, on a new clone of SHARPpy, even after running "python setup.py install".

Any ideas? Thanks!

**Comment by wblumberg** [comment] 2018-06-01 22:43
Perhaps clean out your ~/.sharppy folder?  Are you using the Andover branch?

**Comment by Meteodan** [comment] 2018-06-01 23:31
I switched to the andover branch, deleted, the ~/.sharppy folder, as well as the egg from my python site-packages directory for good measure, and reinstalled it. Still getting the same error :(

**Comment by wblumberg** [comment] 2018-06-02 02:37
Huh. What Anaconda Python version?  2.7 or 3.6?  You sure it's the correct Python path/environment you're running from?

**Comment by Meteodan** [comment] 2018-06-02 03:08
I'm using 2.7, and while I do have a 3.6 environment, I'm almost completely certain it's using the 2.7 environment and the paths are all set correctly. When running setup.py install, it's showing the egg being installed in the 2.7 environment path, etc. I will double check later when I get to the hotel and not bouncing around in the passenger seat of this truck (yes, I'm chasing :) ).

**Comment by Meteodan** [comment] 2018-06-03 02:36
I discovered the problem. My $PYTHONPATH contains a directory with some of my own python modules that don't yet have a home in a package somewhere. One of those modules is named "utils.py", so the import statement in full_gui.py was trying to load that one instead of the one in SHARPpy. 'Doh!

**Comment by wblumberg** [comment] 2018-06-07 00:02
Hmm.  Good to know.  I wonder if we should change the name of that file.  I imagine there are many utils.py files out there that may cause problems.

**Comment by wblumberg** [comment] 2019-11-07 02:17
Closing this.  I've renamed the utils package to sutils.  This should help solve this problem.

**Closed by wblumberg** 2019-11-07 02:17 UTC
