### ISSUE TITLE
Observed soundings won't open Mac and windows 8.1

### ISSUE THREAD

**Issue by Curtis044** [sharppy/SHARPpy#141] opened 2018-07-02 17:28 UTC
I just installed sharppy on a Mac with snow leopard and the observed soundings are blank. The model data is fine and current, I can open any model, but observed data has a blank map. Coincidentally, the same issue occurs on my computer running windows 8.1, however, on my windows 7 computer the observed soundings show up after opening sharppy so I'm not sure why this occurs, but its been this way for a few weeks that I know of. Is anyone else having this issue?

**Comment by Curtis044** [comment] 2018-07-02 17:30
I should add, this is with the compiled binary in all circumstances.

**Comment by tsupinie** [comment] 2018-07-06 03:31
Hmm. I can't reproduce this on my OS X Yosemite machine. If you open ~/.sharppy/sharppy-out.txt, what does it say?

**Comment by Curtis044** [comment] 2018-07-06 03:43
Hi Tim,

When I open that, its blank.

**Comment by kweberUTAH** [comment] 2018-07-10 22:31
I am having the same issue on my 64-bit windows 10 machine with the pre-compiled binary. Worked great for months, then the map for the observed soundings was blank, while the model soundings are fine.

**Comment by georgephillips1** [comment] 2018-07-26 04:37
I'm seeing the same thing with the pre-compiled binary for Win8.1/10.  However, when I run the Win7 binary on Win10, the sounding sites on the map show up for observed soundings.  Looking at the date stamp for the Win8.1/10 version, it's from Aug 8 2015.  The Win7 binary is from May 1 2016

**Comment by mitchellkrogza** [comment] 2018-07-31 11:26
I am new to SharpPy but I think I have the same issue. On Windows 10 I select a dataset for South Africa, I click generate profiles and nothing happens at all 🤔

**Comment by georgephillips1** [comment] 2018-08-01 16:51
@mitchellkrogza Try to download the 64 bit Windows 7 version instead of the Win8.1/Win10 version.  It wouldn't work for me either on the Win8.1/10 version of SHARPpy, but does on the Win7 64bit version.
![southafricasounding](https://user-images.githubusercontent.com/12057398/43536020-613be89e-9570-11e8-94a9-d6c3d87b10ac.png)

**Comment by mitchellkrogza** [comment] 2018-08-01 16:58
Oh awesome thanks, I actually considered trying that yesterday but then got sidetracked.

**Comment by mitchellkrogza** [comment] 2018-08-02 07:52
Thanks @georgephillips1 I downloaded the Windows 7 64 Bit version and voila it works.

![skew-03](https://user-images.githubusercontent.com/9961541/43570118-cdf64a28-9639-11e8-90e4-b51779d75f04.png)

**Comment by iMikeG6** [comment] 2018-08-28 05:03
<img width="989" alt="screen shot 2018-08-28 at 06 49 34" src="https://user-images.githubusercontent.com/42761797/44701513-5e10ba80-aa8f-11e8-9d96-86c8eb10defd.png">
Hi, I also experiencing this issue. I tested it on 4 different Macs. Currently running OS X Sierra 10.12.6. And prior to that, I was using EL Capitan 10.11.x and it was the same. However, on my Surface Pro with Windows 10, the x64 for windows 7 work while the x64 for windows 10 have the same issue that I have on OSX.

**Comment by wblumberg** [comment] 2018-12-16 15:52
Closing this issue because it's been open for longer than 60 days.

**Closed by wblumberg** 2018-12-16 15:52 UTC
